# CRD Godis
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: godises.kumkeehyun.github.com
spec:
  group: kumkeehyun.github.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: "string"
                replicas:
                  type: "integer"
  names:
    kind: Godis
    singular: godis
    plural: godises
  scope: Namespaced
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: godis-controller
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: godis-controller
subjects:
  - kind: ServiceAccount
    name: godis-controller
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: "rbac.authorization.k8s.io"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: godis-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: godis-controller
  template:
    metadata:
      name: godis-controller
      labels:
        name: godis-controller
    spec:
      serviceAccountName: godis-controller
      containers:
        - name: main
          image: kbzjung359/godis
          args:
            - "controller"