# CRD Godis
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: godisclusters.kumkeehyun.github.com
spec:
  group: kumkeehyun.github.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 9
            status:
              type: object
              properties:
                replicas:
                  type: integer
                status:
                  type: string
                initialReplicas:
                  type: integer
                scaleOutID:
                  type: integer
                scaleInID:
                  type: integer

      subresources:
        status: { }
      additionalPrinterColumns:
        - name: SpecReplicas
          type: integer
          description: The replicas spec
          jsonPath: .spec.replicas
        - name: StatusReplicas
          type: integer
          description: The replicas status
          jsonPath: .status.replicas
        - name: Status
          type: string
          jsonPath: .status.status
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  names:
    kind: GodisCluster
    singular: godiscluster
    plural: godisclusters
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: godises.kumkeehyun.github.com
spec:
  group: kumkeehyun.github.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                preferred:
                  type: boolean
            status:
              type: object
              properties:
                state:
                  type: string
      subresources:
        status: { }
      additionalPrinterColumns:
        - name: SpecPreferred
          type: boolean
          description: The preferred spec
          jsonPath: .spec.preferred
        - name: StatusState
          type: string
          description: The state status
          jsonPath: .status.state
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  names:
    kind: Godis
    singular: godis
    plural: godises
  scope: Namespaced
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: godis-controller
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: godis-controller
subjects:
  - kind: ServiceAccount
    name: godis-controller
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: "rbac.authorization.k8s.io"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: godis-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: godis-controller
  template:
    metadata:
      name: godis-controller
      labels:
        name: godis-controller
    spec:
      serviceAccountName: godis-controller
      containers:
        - name: main
          image: kbzjung359/godis
          args:
            - "controller"